{application,issues,
             [{applications,[kernel,stdlib,elixir,logger,httpoison,poison]},
              {description,"issues"},
              {modules,['Elixir.Issues','Elixir.Issues.CLI',
                        'Elixir.Issues.GithubIssues',
                        'Elixir.Issues.TableFormatter']},
              {registered,[]},
              {vsn,"0.1.0"},
              {extra_applications,[logger,httpoison]}]}.
